#!/bin/bash

# Get current timestamp
TIMESTAMP=$(date +"%Y-%m-%d_%H.%M.%S")

# Create output directory with timestamp
OUT_DIR="output/output_$TIMESTAMP"
mkdir -p $OUT_DIR $OUT_DIR/tmp
export OUT_DIR

# Activate conda environment
eval "$(conda shell.bash hook)"

# Check if conda is installed
if ! command -v conda &> /dev/null
then
    echo "conda could not be found"
    exit
fi

# Check if scvelo environment exists. If not, create it and install tools.
if ! conda env list | grep -q "scvelo"
then
    conda config --add channels defaults
    conda config --add channels bioconda
    conda config --set channel_priority strict
    conda create -n scvelo python== -f requirements.txt -y
fi

# TODO what explicit deps
# TODO python version
# TODO environment.yml
# TODO where is scvelo in requirements.txt
